# Generated by Django 5.1.1 on 2024-09-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_reservation_expires_at_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
